docker/images/master/Dockerfile
=> [docker] Avoid git package purge

perceval/backends/core/git.py, tests/test_git.py
The $HOME env variable is where Git looks for the configuration file. So far, Git commands were run without setting this variable. This patch fixes this error and allows to use a configuration file when Git is run.
This patch also fixes #149
=> Run Git commands setting HOME environment variable

perceval/backends/core/github.py, tests/test_github.py
So far, GitHub backend only worked with the GitHub service and
not with GitHub Enterprise instances. With this patch, users
can set the URL on any instance, fetching issues and pull requests
from there.
Backend version updated to 0.10.1.
=> [github] Fix GitHub Enterprise support

README.md, bin/perceval
This pull requests targets #175. It adds instructions to execute launchpad backend.
=> [launchpad] Add instructions to README.md and bin/perceval

perceval/backends/core/phabricator.py, tests/test_phabricator.py
This PR targets issue #178.
The proposed fix assigns null values to the projects which data cannot be accessed
=> [phabricator] Fix restricted access to projects data

perceval/backends/core/git.py, tests/test_git.py
To work with repositories, Perceval always keeps synced
copies of them in local directories (usually under
$HOME/.perceval/repositories). So far, these repositories
were cloned as working repositories. Anyone was able to
modify them; i.e: adding or removing files.
With this patch, Git backend will only work with bared
repositories. This makes easier the synchronization with
the origin and avoids problems with local modifications.
The clone() method will run 'clone' command using the
option '--mirror'.
pull() method is no longer supported and has been replaced
by update(), which runs 'remote update' command to keep
the repository in sync. Prior to this, it was necessary
to run several commands like 'fetch' or 'reset' to have
a similar status like the origin one.
Backend version increased …
=> [git] Work with bared repositories only

perceval/backends/core/meetup.py, tests/test_meetup.py
This PR fixes #183 
The error appears when fetching data from multiple meetup backends with the same token.
The patch introduces a new parameter **throttle_time** which allows the backend to sleep for some time
in case the API returned a _too many requests exception_. This process is executed at most 5 times before returning an error.
By default **throttle_time** is set to 30. 
Find below some code to replicate the issue (the code should be copied in the [test_meetup.py](https://github.com/grimoirelab/perceval/blob/master/tests/test_meetup.py))
```python
import multiprocessing
def test_fetch_live_parallel(self):
MEETUPS = ["Babel-Fish-meetup",
"Belgium-Rust-user-group",
"Blockchain-Meetup-Freiburg",
"Boston-Embedded-Systems-Meetup",
"BostonRust",
"C-C-Bangalore-Meetup", …
```
=> [meetup] Fix too many requests error

perceval/backends/core/gerrit.py
The backend allows now to  initialize the gerrit server port (by default '29418'). In case the gerrit commands return no route host errors (255), the server port can be set to an empty string.
=> [gerrit] Fix no route to host error

perceval/backends/core/telegram.py
The generic client is applied to the Telegram backend. Now connection problems are transparently handled by the generic client.
=> [telegram] Apply generic HTTP client to Telegram

perceval/backends/core/stackexchange.py
The generic client is applied to the Stackexchange backend. Now connection problems are transparently handled by the generic client.
=> [stackexchange] Apply generic HTTP client to Stackexchange

perceval/backends/core/mediawiki.py
The generic client is applied to the Mediawiki backend. Now connection problems are transparently handled by the generic client.
=> [mediawiki] Apply generic HTTP client to Mediawiki

perceval/backends/core/launchpad.py
The generic client is applied to the Launchpad backend. Now connection problems are transparently handled by the generic client.
=> [launchpad] Apply generic HTTP client to Launchpad

perceval/backends/core/dockerhub.py
The generic client is applied to the Dockerhub backend. Now connection problems are transparently handled by the generic client.
=> [dockerhub] Apply generic HTTP client to Dockerhub

perceval/backends/core/meetup.py, tests/test_meetup.py
The generic client is applied to the Meetup backend. Now connection problems are transparently handled by the generic client.
=> [meetup] Apply generic HTTP client to Meetup

perceval/backends/core/git.py
The current code, during the fetch-pack negotiation, sent the
hashes of all the references published by the server. This is
not needed as the client only needs the outdated references
to keep the repository in sync.
This commit reduces the number of 'want' references, sending
the outdated ones only.
Backend version updated to 0.8.9.
Fixes #264
=> [git] Request in fetch-pack the outdated refs only

perceval/backends/core/git.py
So far, this backend was sending the references of the tags
the local server already has. These references are not needed
by the remote server to send the set of new commits. Thus, the
number of references sent to the server are reduced.
Backend version updated to 0.8.10.
=> [git] Send in fetch-pack local heads refs only

perceval/backends/core/bugzilla.py, tests/test_bugzilla.py
This PR allows the Bugzilla backend to store fetched data to archives. Thus it allows to transparently play back previous fetch executions, enabling the recovery of the stored data as it was originally collected from the data source.
=> [bugzilla] Apply archive to Bugzilla backend

perceval/backends/core/github.py, tests/test_github.py
This code allows the GitHub backend to store fetched data to archives. Thus it allows to transparently play back previous fetch executions, enabling the recovery of the stored data as it was originally collected from the data source.
=> [github] Apply archive to GitHub backend

perceval/__init__.py, perceval/archive.py, perceval/backend.py, perceval/errors.py, tests/test_archive.py, tests/test_backend.py, tests/test_errors.py, tests/test_hyperkitty.py, tests/test_pipermail.py
The idea behind the archive manager is to handle a set of `Archive` objects in Perceval. This class manages the creation, deletion and access to this objects
=> Add archive manager

perceval/backends/core/askbot.py, tests/data/askbot/askbot_question_multipage_2.html, tests/test_askbot.py
This code adds the information about answers which have been marked as accepted.
=> [askbot] Add data about accepted answers

perceval/backends/core/askbot.py, perceval/backends/core/bugzilla.py, perceval/backends/core/bugzillarest.py, perceval/backends/core/confluence.py, perceval/backends/core/discourse.py, perceval/backends/core/dockerhub.py, perceval/backends/core/gerrit.py, perceval/backends/core/git.py, perceval/backends/core/github.py, perceval/backends/core/gitlab.py, perceval/backends/core/hyperkitty.py, perceval/backends/core/jenkins.py, perceval/backends/core/jira.py, perceval/backends/core/launchpad.py, perceval/backends/core/mbox.py, perceval/backends/core/mediawiki.py, perceval/backends/core/meetup.py, perceval/backends/core/nntp.py, perceval/backends/core/phabricator.py, perceval/backends/core/pipermail.py, perceval/backends/core/redmine.py, perceval/backends/core/rss.py, perceval/backends/core/slack.py, perceval/backends/core/stackexchange.py, perceval/backends/core/supybot.py, perceval/backends/core/telegram.py, tests/test_jira.py
This PR aligns the signature of the fetch method of each backend to the one provided by the generic backend
=> [backends] Align fetch signature to the backend generic one

perceval/backend.py, perceval/backends/core/askbot.py, perceval/backends/core/bugzilla.py, perceval/backends/core/bugzillarest.py, perceval/backends/core/confluence.py, perceval/backends/core/discourse.py, perceval/backends/core/dockerhub.py, perceval/backends/core/gerrit.py, perceval/backends/core/git.py, perceval/backends/core/github.py, perceval/backends/core/gitlab.py, perceval/backends/core/hyperkitty.py, perceval/backends/core/jenkins.py, perceval/backends/core/jira.py, perceval/backends/core/launchpad.py, perceval/backends/core/mbox.py, perceval/backends/core/mediawiki.py, perceval/backends/core/meetup.py, perceval/backends/core/nntp.py, perceval/backends/core/phabricator.py, perceval/backends/core/pipermail.py, perceval/backends/core/redmine.py, perceval/backends/core/rss.py, perceval/backends/core/slack.py, perceval/backends/core/stackexchange.py, perceval/backends/core/supybot.py, perceval/backends/core/telegram.py, tests/test_backend.py
This PR targets issue #335. It defines the categories accepted by each backend
=> [backends] Add valid categories for backends

perceval/backends/core/gerrit.py
This code enables the gerrit backend to handle archived data
=> [gerrit] Add archive support

perceval/backends/core/mediawiki.py, tests/test_mediawiki.py
This patch sorts payload parameters used for api remote requests to allow the correct retrieval of archived data. Furthermore, it includes in the fetched args stored in the archive also the value of the _test_mode variable. Thus, simplifying the generation of archives for testing purposes.
=> [mediawiki] Force sort request payload parameters

perceval/backend.py, perceval/backends/core/askbot.py, perceval/backends/core/bugzilla.py, perceval/backends/core/bugzillarest.py, perceval/backends/core/confluence.py, perceval/backends/core/discourse.py, perceval/backends/core/dockerhub.py, perceval/backends/core/gerrit.py, perceval/backends/core/git.py, perceval/backends/core/github.py, perceval/backends/core/gitlab.py, perceval/backends/core/hyperkitty.py, perceval/backends/core/jenkins.py, perceval/backends/core/jira.py, perceval/backends/core/launchpad.py, perceval/backends/core/mbox.py, perceval/backends/core/mediawiki.py, perceval/backends/core/meetup.py, perceval/backends/core/nntp.py, perceval/backends/core/phabricator.py, perceval/backends/core/pipermail.py, perceval/backends/core/redmine.py, perceval/backends/core/rss.py, perceval/backends/core/slack.py, perceval/backends/core/stackexchange.py, perceval/backends/core/supybot.py, perceval/backends/core/telegram.py, tests/test_backend.py
This variable is needed to drive the fetching operation in backends with multiple categories (e.g. crates).
=> [backend] Set category when calling fetch and fetch_from_archive

README.md, perceval/backends/core/twitter.py, tests/data/twitter/tweets.json, tests/data/twitter/tweets_page_1.json, tests/data/twitter/tweets_page_2.json, tests/data/twitter/tweets_page_3.json, tests/test_twitter.py
This code includes a backend to fetch tweets from the Twitter Search API. The backend requires a search query (no longer than 500 characters) and a bearer token.
=> [backends] Add backend for Twitter

perceval/backends/core/gitlab.py, tests/test_gitlab.py
This code includes the params `max_retries` and `sleep_time`, which were used by the client, but not initialized in the backend.
=> [gitlab] Fix signature backend

perceval/backends/core/slack.py
This code fixes a flake8 error in the Slack backend.
=> [slack] Fix flake8 error

README.md
I tried to copy+paste the instructions, noticed the filename was wrong. That is all 😄
=> 📝type fix on tests requirements file

perceval/backends/core/gitlab.py, tests/test_gitlab.py
This code allows to prevent perceval to fetch a list of merge or issue ids. Such a blacklist ids can be passed to the GitLab backend using the param`--blacklist-ids`.
=> [gitlab] Allow to blacklist merge/issue ids

README.md
`--token` doesnt work, but `-t` does.
=> Updating instructions for querying stackexchange in README

perceval/backends/core/github.py, tests/data/github/github_issue_2, tests/data/github/github_request_pull_request_2, tests/test_github.py
This PR provides support to fetch issues and pull requests until a given date
included. Test code has been changed accordingly. It addresses https://github.com/chaoss/grimoirelab-perceval/issues/466.
=> [github] Support `to-date` parameter in GitHub backend

perceval/backends/core/git.py, tests/test_git.py
This PR allows to fetch the commits of a repo without performing any update against the target repo. This new feature is enable by setting the fetch param `no_update` to true (by default is disabled). Tests have been created accordingly.
This change is needed to allow ELK to detect the commits that have been deleted in the repo and remove them from the target index (see https://github.com/chaoss/grimoirelab-elk/pull/538)
=> [git] Allow fetch without update repo

perceval/backends/core/confluence.py, tests/data/confluence/confluence_contents.json, tests/test_confluence.py
=> Adding page ancestors to confluence backend

perceval/backend.py
This PR updates the help messages for "from-date" and "to-date" params to include some possible date formats.
Addresses #503.
=> [doc] Update help messages for "from-date" and "to-date" params

perceval/backends/core/gitlab.py, tests/test_gitlab.py
GitLab's backend in Perceval doesn't support Oauth tokens. While in GitHub (or many other backends) you can use the same the Header for Personal Tokens and Oauth Tokens, in GitLab is different ([GitLab Personal tokens](https://docs.gitlab.com/ee/api/#personal-access-tokens), [GitLab Oauth Tokens](https://docs.gitlab.com/ee/api/#oauth2-tokens)).
This contribution includes that feature for Gitlab backend. The user can introduce a token and indicate that is OAuth with the parameter `--is-oauth-token`.
Some tests are included.
Signed-off-by: JJMerchante <jj.merchante@gmail.com>
=> [gitlab] Add support for Gitlab Oauth tokens

perceval/backends/core/slack.py, tests/test_slack.py
This code handles timestamps having more than 6 decimals by rounding their values to the 6th decimal. This change is needed to avoid failures when fetching channels.history data using latest and/or oldest params (which cannot exceed 6 decimals).
=> [slack] Handle timestamps with more than 6 decimals

perceval/backends/core/groupsio.py
This code fixes the docstring of the `api_token` variable. Backend version has been changed accordingly: 0.1.4
=> [groupsio] Fix description `api_token`

README.md, perceval/backends/core/groupsio.py
This code enhances the documentation of the groups.io backend by providing the steps to obtain a token from the groups.io API.
=> [groupsio] Improve documentation to obtain an API token

perceval/backends/core/gitlab.py, tests/test_gitlab.py
This code allows to set from the backend/command line which HTTP status should be retried before raising a HTTP error. By default such status are 500 and 502, they complete the ones already defined in the HttpClient class (i.e., 413, 429, 503).
An example of how to set the retry status from command line is provided below:
```
perceval gitlab coldnight ci-test
--category merge_request
-t xxx
--sleep-for-rate
--extra-retry-status 500 502 503
```
Backend version is set to 0.11.0.
Signed-off-by: Valerio Cosentino <valcos@bitergia.com>
=> [gitlab] Set extra HTTP retry status from backend

perceval/backends/core/jira.py
This code includes some information about the extra data fetched when using an authenticated access. Such a data consists of transitions and operations on issues (e.g., edit-issue, comment-issue).
=> [jira] Add info for data obtained with authenticated access

README.md
This code updates the doc about the Telegram backend. It includes a note concerning the time the messages are available on the Telegram server.
The note has been taken from: https://core.telegram.org/bots/api#getting-updates
=> [telegram] Update doc in README

perceval/backend.py, perceval/backends/core/askbot.py, perceval/backends/core/git.py
Signed-off-by: animesh <animuz111@gmail.com>
Fixed some Typos and Grammatical Error
=> [doc]Fixed Typos and Grammatical Errors

perceval/backends/core/pagure.py, tests/test_pagure.py
This commit fixes failing tests
for Pagure backend.
Signed-off-by: Animesh Kumar <animuz111@gmail.com>
=> [pagure] Fix failing tests

perceval/backends/core/askbot.py, perceval/backends/core/github.py, perceval/backends/core/gitlab.py, perceval/backends/core/gitter.py, perceval/backends/core/googlehits.py, perceval/backends/core/groupsio.py, perceval/backends/core/hyperkitty.py, perceval/backends/core/jenkins.py, perceval/backends/core/jira.py, perceval/backends/core/launchpad.py, perceval/backends/core/mattermost.py, perceval/backends/core/mediawiki.py, perceval/backends/core/pagure.py, perceval/backends/core/stackexchange.py, perceval/backends/core/twitter.py, tests/test_gitter.py, tests/test_groupsio.py
This commit removes string values from client backends
and uses predefined values instead inside the methods.
Signed-off-by: Animesh Kumar <animuz111@gmail.com>
=> [backend] Add predefined paramaters to clients

perceval/backends/core/mbox.py, perceval/backends/core/pipermail.py, tests/test_mbox.py, tests/test_nntp.py
This code fixes flake8 errors which popped up in Travis due to an upgrade of flake8 version,
which is now 3.8.1
=> [perceval] Fix flake8 errors

tests/test_pipermail.py
The test 'test_search_field'  was not really working. It was trying to access 'example.com' URL without mocking the connection with
'httpretty'. Also, the test was wrong because 'metadata_id' is not a method of 'PipermailList'.
=> [tests] Fix pipermail not working search_fields test

README.md, bin/perceval
updated readme for perceval --help
=> Updated readme

poetry.lock, pyproject.toml
Bump grimoirelab-toolkit from 0.1.12 to 0.2.0
=> Bump grimoirelab-toolkit from 0.1.12 to 0.2.0

perceval/backend.py
Using the current documentation, it can be pretty difficult to learn how to appropriately implement a new backend for perceval.  Many of the methods that backends are supposed to implement have no documentation explaining what the methods are supposed to do, or even how their arguments are formatted.
Although it is possible to reverse engineer this information from other backends, this process is time consuming, frustrating, and may deter new developers from being able to use perceval with their application.
This commit expands documentation relating to implementing new backends in several ways:
- The class-level documentation for backends has been expanded to list more of the necessary methods and attributes that backends are responsible for implementing, and additionally lists a brief …
=> [docs] Expand docs for implementing new backends

docs/index.rst, docs/perceval/api-reference.rst, docs/perceval/data-sources.rst, docs/perceval/gerrit.md, docs/perceval/git.md, docs/perceval/github.md, docs/perceval/httpretty.md, docs/perceval/intro.md, docs/perceval/mail-archives.md, docs/perceval/perceval-backends.md
This commit adds documentation from current tutorial.
Since we're revamping old tutorial, we're keeping the
documentation in readthedocs instance.
Signed-off-by: sevagenv <sevagenv@gmail.com>
=> [docs] Add perceval documentation content

perceval/backends/core/git.py, tests/test_git.py
This code allows git to clone repos without SSL certificate.
Test added accordingly.
=> [git] Add --no-ssl-verify parameter

releases/unreleased/[phabricator]-new-blacklist-ids-argument-added.yml
Signed-off-by: Jose Javier Merchante <jjmerchante@bitergia.com>
=> Restore changelog entries from release candidate

perceval/backends/core/git.py
This PR removes one underscore to some Git backend methods to allow overriding them in subclasses.
=> [git] Update Git private methods
