chaoss/grimoirelab-perceval

perceval/backends/git.py
tests/data/git_bad_cr.txt
tests/test_git.py

In some commit messages, there is a carriage return character
not in the end of a line. This caused a wrong line break which
caused the parser to misidentify the end of the message.
Fixes #21

[git] Fix carriage return not in end of line

---

perceval/backends/core/discourse.py
tests/data/discourse_topics_last_posted_at_null.json
tests/test_discourse.py

This error is described at 
https://github.com/grimoirelab/perceval/issues/150
and it can be reproduced with:
`perceval discourse https://discourse.mozilla.org/`
This PR fixes it.

[discourse] Do not process topics with last_posted_at = None

---

perceval/backends/core/github.py
tests/data/github/abuse_rate_limit
tests/test_github.py

This pull request extends the github backend to deal with [abuse rate limit exceptions](https://developer.github.com/v3/#staying-within-the-rate-limit).
In a nutshell, if an abuse rate limit exception is triggered when querying the API, the backend sleeps for the number of seconds reported in the **retry-after** header field. This process is repeated at most 5 times (**MAX_RETRIES** in GitHubClient), before the backend stops and returns an error.

[github] Fix abuse rate limit error

---

perceval/backends/core/git.py

Fix for flake8 error: 
- ./perceval/backends/core/git.py:643:13: E741 ambiguous variable name 'l'
This error is probably related to a new release of flake8 (2017-10-23)

[git] Fix flake8 error

---

perceval/backends/core/github.py

This PR fixes issue #187. It enables to fetch reactions information without providing an API token

[github] Enable fetch reactions without token

---

README.md
perceval/backends/core/git.py
requirements.txt
setup.py

The command 'fetch-pack' only works with the TCP (git://)
protocol unless '--stateless-rpc' flag is active, the caller
has established a connection with the server using HTTP
and a pipe to it.
Some Git servers do not let to talk to them using TCP
protocol, only using HTTP(s) on top of it.
To fix this issue, dulwich library has been used. It allows
to talk to Git repositories without calling git commands
directly. In this particular case, it is able to fetch
packs using any protocol.
This would be the first step to replace Git commands by
calls to a pure Python library.

[git] Fix fetch-pack for HTTPs connections

---

perceval/backends/core/git.py

Mirrors can contain references and objects that are not part
of the real activity in the repositories. For instance, GitHub
repos have references to all the pull requests submitted (merged
or not).
This patch fixes that problem, cloning and updating repositories
in `bare`  way.
Backend version updated to 0.8.4.

[git] Change 'mirror' to 'bare' repositories

---

perceval/backends/core/git.py
tests/test_git.py

The current code sends, during the fetch-pack negotiation,
the hash for all the commits that the client has. This is not
needed. Only head hashes are usually needed by the server
to determine which objects needs to send back to the client.
In big repositories, this may hang the communication.
This commits adds a simple graph walker which only sends
the current hashes for each 'refs/heads/' or 'refs/tags/'
available in the client repository.
Backend version updated to 0.8.5.

[git] Limit the number of 'have' commits sent by fetch-pack

---

perceval/backends/core/git.py
tests/test_git.py

The command 'show-ref' returns an error when is run in
empty repositories.
This patch checks whether the repository is empty before
checking the references, raising an exception on that case.
Backend version updated to 0.8.6.

[git] Fix error fetching latest items from empty repositories

---

perceval/backends/core/git.py

When 'git://' URLs were in use, the initialization of TCPGitClient
instances were wrong because the host given to it was invalid.
When an instance tryed to connect to a Git host, the code raised
a "Name of service not known" error.
To fix this bug, we delegate to dulwich the initialization
of clients according to the protocol that will be used.
This PR fixes #210

[git] Fix invalid URL when TCPGitClient is initialized

---

perceval/backends/core/github.py
tests/data/github/rate_limit
tests/test_github.py

This PR includes a method to initialize rate limit data to avoid starting a fetching process with an exhausted token.

[github] Init rate limit info (requests left and reset time)

---

perceval/backends/core/slack.py

The generic client is applied to the Slack backend. Now connection problems are transparently handled by the generic client.

[slack] Apply generic HTTP client to Slack

---

perceval/backends/core/rss.py

The generic client is applied to the RSS backend. Now connection problems are transparently handled by the generic client.

[rss] Apply generic HTTP client to RSS

---

perceval/backends/core/jira.py
tests/test_jira.py

The generic client is applied to the Jira backend. Now connection problems are transparently handled by the generic client.

[jira] Apply generic HTTP client to Jira

---

perceval/backends/core/jenkins.py
tests/test_jenkins.py

The generic client is applied to the Jenkins backend. Now connection problems are transparently handled by the generic client.

[jenkins] Apply generic HTTP client to Jenkins

---

perceval/backends/core/discourse.py
tests/test_discourse.py

The generic client is applied to the Discourse backend. Now connection problems are transparently handled by the generic client.

[discourse] Apply generic HTTP client to Discourse

---

perceval/backends/core/confluence.py

The generic client is applied to the Confluence backend. Now connection problems are transparently handled by the generic client.

[confluence] Apply generic HTTP client to Confluence

---

perceval/backends/core/bugzillarest.py

The generic client is applied to the Bugzillarest backend. Now connection problems are transparently handled by the generic client.

[bugzillarest] Apply generic HTTP client to Bugzillarest

---

perceval/backends/core/bugzilla.py
tests/test_bugzilla.py

The generic client is applied to the GitHub backend. Now connection problems are transparently handled by the generic client.

[bugzilla] Apply generic HTTP client to Bugzilla

---

perceval/backends/core/phabricator.py
perceval/client.py
tests/test_phabricator.py

The generic client is applied to the Phabricator backend. Now connection problems are transparently handled by the generic client. Note that the fetch method in the generic client has been extended with an additional parameter (verify) used to enable/disable SSL verification.

[phabricator] Apply generic HTTP client to Phabricator

---

perceval/backends/core/askbot.py
tests/test_askbot.py

The generic client is applied to the Askbot backend. Now connection problems are transparently handled by the generic client.

[askbot] Apply generic HTTP client to Askbot

---

perceval/backends/core/jenkins.py

This patch initializes the error status codes list by value. Before the list was initialized by reference, causing failures of some tests in other backends (launchpad).

[jenkins] Fix status codes in client

---

perceval/backends/core/redmine.py
perceval/client.py

The generic client is applied to the Redmine backend. Now connection problems are transparently handled by the generic client. Note that this PR shares with PR #236 some code (which extends the fetch method of the generic client).

[redmine] Apply generic HTTP client to Redmine

---

perceval/backends/core/hyperkitty.py
tests/test_hyperkitty.py

The generic client is applied to the HyperKitty backend. Now connection problems are transparently handled by the generic client.

[hyperkitty] Apply generic HTTP client to HyperKitty

---

perceval/backends/core/launchpad.py
tests/test_launchpad.py

This patch allows to handle 404 http errors, which may occur when requesting data of deleted user.

[launchpad] Handle 404 HTTP error

---

perceval/backend.py

This function uses the class method `__subclasses__` to get
derived classes from Backend and BackendCommand. The problem
with this method is it only returns direct/children subclasses,
not grandchildren classes.
MBox is a children of Backend class while Pipermail and Hyperkitty
are children of MBox and grandchildren of Backend. So far, only
MBox was found because it's a direct subclass of Backend.

Fix 'find_backends' to get all backend descendants (Fix #257)

---

perceval/backends/core/meetup.py
tests/test_meetup.py

This is a work around to fix the problem with Meetup API.
In some cases, having this status in the list of requested
events, makes the API to return zero events.
The bug was reported in https://github.com/meetup/api/issues/260.
As soon as it gets fixed, we will add it back again to the list
of requested events.
Backend version updated to 0.7.0.
Partially fixes #261

[meetup] Remove 'draft' status due to a bug in Meetup API

---

perceval/client.py
tests/test_client.py

This patch fixes the log message generated when updating the rate limit reset. The log now stores the output defined by the method calculate_time_to_reset.

[http-client] Fix rate limit reset log message

---

perceval/backends/core/nntp.py
tests/data/nntp/nntp_1.txt

This patch fixes the error related to a wrong coding of the key of the date field ('DATE' instead of 'Date') in the articles returned by the API. The patch allows to look firstly for a 'Date' key and if not found for a 'DATE' key.

[nntp] Fix KeyError 'Date' in metadata_updated_on field

---

perceval/backend.py
tests/test_backend.py

This patch fixes the name of the backend used to initialize the archive metadata.

[backend] Fix backend name in fetch method

---

perceval/backend.py

The functionality of this decorator was moved to Backend class
when the generic client was incorporated to the code. This decorator
was still needed by the cache. Since this feature has been removed
the decorator is not longer needed.

[backend] Remove metadata() decorator

---

perceval/backend.py
tests/test_backend.py

This error was raised when Perceval was run from the command line
with those backends which don't support the archive mode.
This patch fixes #327

[backend] Fix 'Namespace' object has no attribute 'fetch_archive'

---

perceval/backend.py
tests/test_backend.py

This patch handles the errors produced by `fetch()` and `fetch_from_cache()`. In the first case, when there's an error in fetch(), if an archive was created to store data it will be removed. For the second case, errors produced reading an archive file will be ignored. The archive will be skipped and the process will continue reading the next archive of the set.

Handle archive errors

---

perceval/backends/core/mbox.py
tests/test_mbox.py

This variable is not created when an error occurs copying mboxes.
It makes the code fail because the finally block that handles
OSError exceptions requires that variable.
Aditionally, this commit improves the test where this copything
mboxes functionality is tested. So far, the test would fail when
super users run it.
Backend version updated to 0.9.1

[mbox] Define 'tmp_path' variable before copying mboxes

---

perceval/backends/core/mediawiki.py

This patch sorts payload parameters used to query mediawiki server versions >= 1.27, thus allowing the correct retrieval of archived data.

[mediawiki] Sort request payload parameters for versions >= 1.27

---

perceval/backend.py
tests/test_backend.py

The 'category' argument does not have a default value. When
parameters are parsed and a category is not given, its value
is set to 'None'. This caused an error due to backends
do not consider this value as a valid category.
This patch removes the category from the parsed parameters
when the value is empty or None.

[backend] Remove empty category from parsed arguments

---

perceval/backends/core/pipermail.py
tests/test_pipermail.py

This patch targets issue #358. It enables the handling of inaccessible archive URLs. Thus, a warning is logged when a 403 HTTP error is returned and the archive is skipped.

[pipermail] Handle inaccessible archive URLs

---

perceval/backends/core/github.py
perceval/backends/core/gitlab.py
perceval/backends/core/meetup.py
perceval/client.py
tests/test_client.py
tests/test_github.py
tests/test_gitlab.py
tests/test_meetup.py

This patch fixes issue #355. It prevents to sleep for a negative number of seconds when waiting for tokens rate limit reset. The error seems to occur when a given token is shared among several fetching processes.

[client] Avoid negative sleep time error for rate limit reset

---

perceval/backends/core/jenkins.py
tests/test_jenkins.py

This patch allows to control the granularity of the data returned by the Jenkins API. By default this value (detail_depth) is set to 1. Note that increasing the detail_depth may considerably slow down the fetch operation and cause connection broken errors.

[jenkins] Control detail level of Jenkins data

---

perceval/backends/core/phabricator.py
tests/data/phabricator/phabricator_transactions.json
tests/test_phabricator.py

This patch allows to handle different JSON structures (dict and list) of how project data appears in old and new values within the transactions core:edge.

[phabricator] Handle project info in core:edge transactions

---

bin/perceval
perceval/__init__.py
perceval/backends/core/__init__.py
setup.py
tests/test_backend.py

This module was not really using package namespaces. This patch should provide that support. For that, some changes had to be done to the module itself, mainly changing __init__.py in perceval and perceval/backends to contain only the line for declaring namepaces. This means that symbols that were exported by those __init__.py files now need to be imported from the corresponding modules. In particular, __version__ is now provided by perceval.backends.core for this package.
All of this has bin fixed in bin/perceval, but maybe other packages (GrimoireELK, SirArthur, Mordred) would need similar fixes.

Fix support for package namespaces.

---

setup.cfg
setup.py

The command
```
python setup.py test
```
was not working.
This patch makes it work.

[setup] Fix to let setup.py test run

---

perceval/backends/core/pipermail.py
tests/test_pipermail.py

This code allows to disable SSL verifications for calls to a pipermail server, via the argument `verify` (default value is set to true). Note that if verification is disabled, warnings are returned in the log.

[pipermail] Disable SSL verification

---

perceval/backends/core/pipermail.py
tests/test_pipermail.py

This code fixes the way how SSL verification is passed via command line (enabled by default). Verification can be disabled by passing `no-verify` as parameter.

[pipermail] Fix command line parameters

---

perceval/backend.py
tests/test_backend.py

This code changes the signature of the function `fetch_from_archive`, which now includes the category within the backend args.
Tests have been changed accordingly.

[backend] Include category in backend params

---

tests/test_backend.py

This PR addresses #394. It replaces the datetime function used in the method `test_decorator` with its equivalent available in grimoirelab-toolkit. Thus, improving in this way the coherence in the code.

[tests] Replace datetime function with equivalent toolkit one

---

perceval/backends/core/twitter.py

This code sets the metadata_id attribute to `id_str`. As [reported](https://twittercommunity.com/t/twitter-id-and-id-str-are-different/79942/9) by the Twitter API, `id_str` should be used in preference of `id`, because some programming languages may otherwise scramble the ID.

[twitter] Change metadata_id attribute

---

perceval/backends/core/twitter.py
tests/test_twitter.py

This code allows the backend to handle too many request exceptions (429).

[twitter] Handle too many requests error

---

perceval/backends/core/twitter.py
tests/test_twitter.py

This code prevents to store the api token within the archive, thus allowing to fetch data from an archive without the need of passing a real token.

[twitter] Add sanitize method

---

tests/test_mbox.py

This code fixes the assertion in the method `test_mboxes_error`, which is currently failing.

[mbox] Fix test `test_mboxes_error`

---

perceval/backends/core/gitlab.py
tests/test_gitlab.py

This code removes token information before archiving the GitLab data, thus it enables to read the archive afterwards without the need of passing the token.

[gitlab] Sanitize requests before archiving

---

perceval/backends/core/askbot.py
tests/test_askbot.py

This code allows to handle 500 http errors returned by the upstream server when fetching comments of answers, which caused perceval to fail. Now those comments are skipped and a warning message is logged.

[askbot] Handle upstream internal server

---

perceval/backends/core/github.py
tests/test_github.py

This code sets the maximum number of items retrieved per page to 100 (the current limit provided by the GitHub API). Thus, it allows to reduce the number of token requests (useful for repos with many issues and prs).

[github] Increase number of items retrieved per page

---

perceval/backends/core/mediawiki.py
tests/data/mediawiki/mediawiki_page_476589_revisions.json
tests/data/mediawiki/mediawiki_page_476590_revisions.json
tests/data/mediawiki/mediawiki_pages_all.json
tests/data/mediawiki/mediawiki_pages_allrevisions.json
tests/data/mediawiki/mediawiki_pages_recent_changes.json
tests/test_mediawiki.py

This code targets #436, thus it optmizes the number of calls to fetch revision info, in particular if a page doesn't have any revision, the call is not performed. Furthermore, this code avoids errors when creating the archive (which doesn't allow to store duplicated API calls).

[mediawiki] Optimize number of calls to API

---

perceval/backends/core/gitlab.py
tests/test_gitlab.py

This code fixes the return value of the `has_resuming` method, which now is set to true.

[gitlab] Fix `has_resuming` method

---

perceval/backends/core/gitlab.py

This code allows the backend to reissue petititions to the GitLab API in case of 503 HTTP errors. This fix is needed to avoid the fetching process to be stopped due to upstream server problems.

[gitlab] Add retry on 503 HTTP errors

---

perceval/backends/core/git.py
tests/test_git.py

This code adds support for the `rev-list` command, thus the list of commit hashes is retrieved from the repo without triggering any update. The rev-list is executed with the following params by default:
`git rev-list --topo-order --branches --tags --remotes=origin`.
However, using the param `branches`, it is possible to analysis a set of branches.

[git] Add rev-list command to GitRepository class

---

perceval/backends/core/github.py
tests/data/github/rate_limit_aaa
tests/data/github/rate_limit_bbb
tests/test_github.py

This adds support for multiple GitHub tokens for Perceval GitHub backend.
This is backward compatible.
You're specifying token as a string. If your token is just a single 40-hex-digit token then tokens pool will just have that single token. If your token is a comma-separated list of 40-hex-digit tokens that all tokens will be used when performing GitHub API calls.
Token with most API points will be used for each request. Checking for the best token happens every time you use 10% of the current token's remaining API points.
Changes are as small as possible and as compatible as possible, you can use Perceval GitHub without any changes at all, it will only be more immune to API points limit when providing more API tokens.
Signed-off-by: Lukasz Gryglicki <lukaszgryglicki@o2.pl>

Add support for GitHub tokens pool

---

perceval/backends/core/discourse.py
tests/test_discourse.py

This code enhances the Discourse backend, client and commandline with the params `sleep_time` and `max_retries`, which slow down the number of petititions issued to the API, and thus limit possible 429 HTTP errors. Tests have been changed accordingly.

[discourse] Add params `sleep_time` and ` max_retries`

---

perceval/backends/core/discourse.py
perceval/backends/core/gitlab.py
perceval/backends/core/googlehits.py
perceval/backends/core/jenkins.py
perceval/backends/core/launchpad.py
perceval/backends/core/mattermost.py
perceval/backends/core/meetup.py
perceval/backends/core/phabricator.py
perceval/backends/core/twitter.py
perceval/client.py
tests/test_discourse.py

This code updates the description of the `sleep_time` param for the client and the following backends:
- gitlab
- googlehits
- jenkins
- launchpad
- mattermost
- meetup
- phabricator
- twitter

[doc] Update docstring for `sleep_time` param

---

perceval/backends/core/git.py
tests/test_git.py

This code fixes the call of the git command `rev-list` with parameter `--max-count`, which needs to be prepended with `--branches` or `--tags`.

[git] Fix `rev-list` call with `--max-count`

---

perceval/backend.py
perceval/backends/core/meetup.py
perceval/backends/core/nntp.py
perceval/backends/core/telegram.py
tests/test_backend.py
tests/test_meetup.py

This PR addresses the requirements defined in #490.
Classified fields can be declared using `CLASSIFIED_FIELDS` class attribute. This attribute will contain a list of lists. Each list stores the "path" or nested dicts keys to the field to filter. For example:
`['my', 'classified', 'field']` will remove `field` from `item['data']['my']['classified']` dict.
To filter this fields from the resulting items, `fetch()` method adds a new parameter `filter_classified`.
Classified fields can also be removed from the command line with the option `filter-classified`.
To start with new feature, this PR adds the field `group.topics` to the list of classified fields in Meetup backend. This field is considered sensible for some related groups working with GrimoireLab.

Option to filter classified data

---

perceval/backends/core/confluence.py
tests/data/confluence/confluence_content_1_v2.json
tests/data/confluence/confluence_content_1_v3.json
tests/test_confluence.py

This PR allows to skip the historical contents not having the 'when' attribute, which is used to calculated the `updated_on` value of the JSON output produced by Perceval.

[confluence] Skip contents if 'when' attribute is missing

---

docs/conf.py
perceval/backends/core/nntp.py
perceval/utils.py

This code removes unused imports from the files docs/conf.py and perceval/utils.py. Furthermore it changes the import `email.parser` (which was not needed) to `email` in the NNTP backend and it updates its version to 0.5.3.

Removes unused imports

---

README.md
bin/perceval
perceval/backends/core/github.py

This code updates the information about the categories of the github and gitlab backends in the README and bin/perceval. Furthermore, it improves the docstrings of the methods `pulls` and `issues` of the GitHubClient.
Please check and suggest me changes if you need any. I would be happy to make the changes in this same PR.
@jgbarah @valeriocos 
Sorry for the delay in PR as I was busy with some exams in the last week.
Solves #494 if this pr is merged.

[doc] Update documentation for github and gitlab backends

---

perceval/backends/core/github.py
tests/data/github/github_request_pull_request_2_comments
tests/test_github.py

Fixes #507, #459.
This PR tries to fix the error for ghost user data by making the required changes in github.py, add modifies  github_request_pull_request_2_comments and test_github.py to  add the required tests.
It keeps the comments data while setting the user to `None` for ghost user.

Fix error for ghost user data

---

perceval/backends/core/jira.py
tests/data/jira/jira_comments_issue_empty.json
tests/data/jira/jira_comments_issue_page_1.json
tests/data/jira/jira_comments_issue_page_2.json
tests/data/jira/jira_issues_page_1.json
tests/data/jira/jira_issues_page_2.json
tests/data/jira/jira_issues_parse_expected.json
tests/test_jira.py

This PR allows to include comments of Jira issues. Comments are retrieved using the API endpoint `/rest/api/2/issue/<issue-id>/comment`. Previous tests have been modified and new ones have been added accordingly. Furthermore, this PR includes also a commit which increases the test coverage of the Jira backend, which now is 100%.

[jira] Add comments in issues

---

perceval/backends/core/github.py
tests/data/github/github_request_pull_request_1_reviews
tests/data/github/github_request_pull_request_2_reviews
tests/test_github.py

This feature enables the fetching of reviews for each pull request using the api-call: `https://api.github.com/repos/<user-name>/<repo-name>/pulls/<pull-id>/reviews`. The reviews are stored in the "reviews_data" attribute. 
This is a fix for #516

[github] Include reviews in pull request data fetched by Perceval

---

perceval/backends/core/gitlab.py
tests/test_gitlab.py

For efficiency reasons the GitLab API doesn't include the attribute `last` in the pagination responses for
calls with more than 10,000 items. Thus, this code allows to handle this case, tests have been added
accordingly.

[gitlab] Handle missing attr `last` in pagination response

---

perceval/backends/core/github.py
tests/data/github/github_enterprise_request_requested_reviewers
tests/test_github.py

Fixes #523
This PR handles cases where Github Enterprise servers may return a list of users for `/repos/{org}/{repo}/pulls/{number}/requested_reviewers` instead of the dict referenced [here](https://developer.github.com/enterprise/2.16/v3/pulls/review_requests/).
Test run: https://travis-ci.org/cewilliams/grimoirelab-perceval/builds/530053609

Handle Github Enterprise returning list instead of dict for reviewers

---

perceval/backends/core/gitlab.py

The module `requests` sometimes tries to guess the encoding of the responses received. It uses the module `chardet` to determine the encoding. In the case of GitLab it is unable to determine the encoding and usually produces bad guesses as Big5 encoding when all it is encoded as UTF-8.
As we know GitLab encodes in UTF-8, this commit forces to parse the response using that encoding.

[gitlab] Force UTF-8 encoding on response contents

---

perceval/backends/core/groupsio.py
tests/test_groupsio.py

The request to retrieve the list of groups a user is subscribed to was wrong. The parameter 'limit' was set wrongly to the user authentication data. This commit fixes that bug.
Backend version updated to 0.1.3.

[groupsio] Fix invalid value for 'limit' in subscriptions query

---

perceval/backends/core/gitlab.py
perceval/backends/core/meetup.py
tests/test_meetup.py

Due to the deprecation of api key usages, this code allows to use oauth tokens to access the meetup API. The procedure to obtain an oauth token is assisted by the following script:
https://gist.github.com/valeriocos/e16424bc7dc0f2d6dd8bb9295c6f9a4b
Tests have been enhanced accordingly. The backend version is now 0.14.0

[meetup] Enable oauth token use

---

perceval/backends/core/mediawiki.py
tests/data/mediawiki/mediawiki_pages_recent_changes.json
tests/test_mediawiki.py

This PR skips pages not having the `pageid` attribute. This may be the case for pages of type `log` with `actionhidden` attribute. Tests have been added accordingly.
Backend version is now 0.9.6

[mediawiki] Skip page without `pageid` attribute

---

perceval/backends/core/jenkins.py
perceval/client.py
tests/test_client.py
tests/test_jenkins.py

This PR allows to fetch builds and jobs available via a Jenkins server, which requires authenticated access.
Tests have been added accordingly. The backend version has been set to 0.12.0.

[jenkins] Support authenticated access using user/API token

---

perceval/backends/core/slack.py
tests/data/slack/slack_info_archived.json
tests/test_slack.py

Due to an API change, the number of members for archived channels cannot be retrieved anymore. This code set the `num_members` value of archived channels to None, and logs a warning message.
Tests have been added accordingly. The backend version is set to 0.7.3.
Signed-off-by: Valerio Cosentino <valcos@bitergia.com>

[slack] Handle `num_members` for archived channels

---

README.md
requirements_tests.txt
setup.py

This PR tackles https://github.com/chaoss/grimoirelab-perceval/issues/557. It unpins the httpretty dependency, since the bug in version 0.8.14, which was preventing to execute some tests in Perceval, is solved in version 0.9.6. Furthermore, the README has been updated accordingly.

[tests] Update httpretty dependency

---

tests/test_backend.py

This code fixes the return value of the MockedBackend.metadata_updated_on, which wasn't
set to a timestamp. The assertions in the tests `test_metadata` and `test_metadata_classified_fields`
within TestMetadata class have been changed accordingly.

[tests] Fix metadata_updated_on of MockedBackend

---

README.md

This PR addresses https://github.com/chaoss/grimoirelab-perceval/issues/535. In a nutshell, `git` and `build-essential` are listed in the requirements section .

[doc] Add git and build-essential to requirements section

---

perceval/backends/core/github.py
tests/data/github/github_request_requested_reviewers_ghost
tests/test_github.py

This PR addressed https://github.com/chaoss/grimoirelab-perceval/issues/590. Thus it handles `None` values for requested reviewers. Before accessing the login attribute, a condition checks that the reviewer is not None and the `login` attribute exists.
An example of this behaviour is visible at: hyperledger/sawtooth-core#93, where the last requested
reviewer (on the right side) is None, and only a yellow circle (without name) is shown on the web page.
Backend version is now 0.24.1
This PR includes also a minor fix wrt variable names used in some github tests.

[github] Handle `None` requested reviewers

---

perceval/backends/core/jenkins.py
tests/data/jenkins/jenkins_job_builds.json
tests/data/jenkins/jenkins_job_no_builds.json
tests/data/jenkins/jenkins_jobs.json
tests/data/jenkins/jenkins_workflow_job_builds.json
tests/data/jenkins/jenkins_workflow_jobs.json
tests/test_jenkins.py

This code allows to process workflow multibranches job, which include nested jobs and their corresponding builds.
Since the API doesn't offer an endpoint to retrieve workflow jobs, the backend leverages on the class type of the job to process it accordingly. Thus, if the class type is `WorkflowMultiBranchProject`, the nested jobs are retrieved one by one and their builds obtained. Otherwise the logic to process the job is left as it was.
Backend version is now 0.15.0

[jenkins] Handle workflow multibranch job builds

---

perceval/backends/core/discourse.py
perceval/backends/core/gitlab.py
tests/test_discourse.py
tests/test_gitlab.py

This code allows to raise a Client error when the `token` variable is `None` and `is_oauth_token` is True.
Backend version is now 0.11.1.

[gitlab] Raise client error if oauth is set and token is not

---

perceval/backends/core/jenkins.py
tests/test_jenkins.py

This code changes the level of the message logged when no builds are found for a job to `debug`. This
change is needed to reduce the size of logs produced when running grimoirelab.
Tests have been modified accordingly.

[jenkins] Log debug message when builds are not found

---

README.md
perceval/backends/core/groupsio.py
tests/test_groupsio.py

This PR addresses #607. It allows to collect a list of messages sent after a given date (included) from the groupsio API. The backend `from_date` parameter is propagated to the client, which sends it to the API endpoint to download archives. This change is made possible after a recent change in the upstream API, and allows to improve the performance of the fetching operation.
Backend version is now 0.3.2.

[groupsio] Fetch messages after a given date

---

perceval/backends/core/telegram.py
tests/data/telegram/telegram_messages_next.json
tests/test_telegram.py

This issue address #614, thus it handles the edited messages in Telegram. In a nutshell, the edited information is included in a message and the latter is marked as edited (using the boolean attribute `edited` within the message).
Backend version is now 0.11.1

[telegram] Handle edited messages

---

docker/images/README.md

This commit fixes broken link in
README.md of docker/images
Signed-off-by: animesh <animuz111@gmail.com>

[doc] Fix broken link in README

---

perceval/backends/core/groupsio.py
tests/test_groupsio.py

This code forces the format of the from_date value to utc+0 timezone. This change is needed since the groupsio API expects to receive a start date with tzinfo.
Backend version is 0.4.1.
Tests have been updated accordingly.

[groupsio] Format from_date with utc+0 timezone

---

perceval/backends/core/gerrit.py
tests/data/gerrit/gerrit_version_313
tests/test_gerrit.py

This code extends the `--start` param, used to perform the incremental fetch of gerrit reviews, to
gerrit instances with versions 3.x (tested with 3.1.x).
Backend version is now 0.13.1.
Fixes #633

[gerrit] Extend `--start` param to gerrit 3.x

---

README.md
bin/perceval
perceval/backends/core/rocketchat.py
releases/unreleased/add-rocket.chat-backend.yml
tests/data/rocketchat/channel_info.json
tests/data/rocketchat/message_empty_2020_05_10.json
tests/data/rocketchat/message_page_1.json
tests/data/rocketchat/message_page_2.json
tests/data/rocketchat/message_page_2020_05_03.json
tests/test_rocketchat.py

Fixes: #543 
This commit adds support to fetch
messages from a Rocket.Chat channel.
The tests have been added accordingly.
The usage docs have been updated.
Signed-off-by: Animesh Kumar <animuz111@gmail.com>

[backend] Add Rocket.Chat backend

---

perceval/backends/core/slack.py
tests/test_slack.py

This change is needed since the new endpoint `conversations.history` doesn't include replies among the messages fetched from the API. There isn't enough documentation to understand whether this exclusion is a bug. The document that contains
deprecation info only mentions that `channels.history` is replaced by `conversations.history`: https://api.slack.com/changelog/2020-01-deprecating-antecedents-to-the-conversations-api
As found on the Web, it seems that the endpoint `conversations.history` stopped returning replies since 2020-04-17: https://www.bakejam.com/slacks-conversationshistory-api-ignores-replies/
The `channels.history` endpoint will work until Feb 2021 and won't work with apps created after June 10th 2020 (ref: https://api.slack.com/methods/channels.history).

[slack] Use channels.history to retrieve message

---

perceval/backends/core/gerrit.py
tests/test_gerrit.py

This adds `--ssh-id-filepath` Perceval Gerrit backend option. You can use it to allow running multiple Gerrit backends in parallel, each having its own SSH private key.
Fixes #681 
Signed-off-by: Łukasz Gryglicki <lukaszgryglicki@o2.pl>

Add support for specifying Gerrit SSH key location, fixes #681

---

README.md
requirements.txt
setup.py

Running Perceval with Python 3.8 and dulwich <0.19.6 raises an Exception because a method has been deprecated and removed.
This commit updates the version of `dulwich` to the latest one
Related to: https://github.com/chaoss/grimoirelab-perceval/issues/687

Update dulwich package version

---

perceval/backends/core/slack.py
tests/data/slack/slack_user_U0004_private.json
tests/test_slack.py

This code allows fetching message from a private user and set
the `user` data as `None`.

[slack] Fix fetch message from a private user

---

perceval/backends/core/supybot.py
tests/data/supybot/supybot_date_without_tz.log
tests/test_supybot.py

Supybot is deprecated and the logs generated by its successor,
Limoria, do not contain timezone information.
Test failing when no timezone information was given has been modified
to pass now.
An additional log file based on the issue report #709 has been added
to the test suite.
Resolves: #709
Signed-off-by: Gregorio <grex@gsyc.urjc.es>

[supybot] Adds support for logs without timezone information

---

poetry.lock
pyproject.toml

This commit adds the files required to add poetry support to perceval.
This update is required to start using the Bitergia/release-tools for automating the GrimoireLab toolset releases.

 [perceval] Add poetry support

---

perceval/backends/core/slack.py
tests/test_slack.py

This reverts commit fb075a88ce495e65a1e87462f9dd7e662300ddad.
Signed-off-by: linonymous

Revert "[slack] Use channels.history to retrieve message"

---

perceval/backends/core/stackexchange.py
tests/test_stackexchange.py

This change is required to retrieve items incrementally.
Backend version is 0.12.1.

[stackexchange] Change the fetch order to 'asc'

---

pyproject.toml

This PR adds the setuptools version to the poetry setup configurations. This is needed to fix the `No module named "setuptools"` bug.
Fixes https://github.com/chaoss/grimoirelab-perceval/issues/720
Signed-off-by: Venu Vardhan Reddy Tekula <venu@bitergia.com>

[poetry] Add setuptools to the build-system

---

poetry.lock
pyproject.toml

This commit adds the `flake8` and `coverage` to the development dependencies. These would be installed along with the other dependencies using `poetry install`.

[deps] Add flake8 and coverage to dev dependencies

---

.github/workflows/ci.yml

This commit enables to use of poetry for the installation of the dependencies & tool and running the test-suite in the CI github actions workflow. This is needed as we are migrating the GrimoireLab tools to using poetry.

[CI] Use poetry for the CI github actions workflow

---

perceval/backends/core/github.py
tests/test_github.py

Return an empty list when requesting a list of orgs of a login and GitHub API returns a 403 Unauthorized.
I wasn't sure why a 403 error code should force a retry, I removed it from the list of `EXTRA_STATUS_FORCELIST`
Fixes: #733

[github] Fix user_orgs for organizations with restricted access

---

perceval/backends/core/github.py
tests/test_github.py

This code fixes when user is no longer exists or the token
doesn't have permission to get the information.
Test added accordingly.

[github] Fix 404 Client Error when user is not found.

---

README.md

This PR adds the list of open-source community backends, implemented for perceval, to the README.md file. This would highlight the work of the contributors for creating support for more data sources.

Add community backends list to the README.md

---

README.md

The OSF perceval backend was forked from the weblate backend, and developed primarily by Open@RIT member @suhascv, with some contributions from me.  It currently supports collecting a number of global statistics about OSF, as well as activity logs and forks for specific projects.
This commit adds a link to the perceval-osf backend to the list of community-maintained backends in the README.  We at open@rit would greatly appreciate the inclusion!
—Emi

[docs]  Add OSF community backend

---

perceval/backends/core/mattermost.py
tests/data/mattermost/mattermost_channel.json
tests/test_mattermost.py

The current mattermost backend runs using a channel ID in order to select which channel is being scraped.  However, this can get in the way in certain circumstances.  Mainly, the channel ID can't be derived from a mattermost URL like
https://my-mattermost.link/some-team/channels/some-channel
This PR allows the mattermost backend to be called with a team name and a channel name as an alternative to the normal behavior.
This means that tools like grimoirelab-elk would be able to accept a normal mattermost URL instead of requiring a unique repository format, which would improve intuitivity.  Additionally, the channel/team names are easier for users to find than the channel ID, which means a smoother user experience.
This does not break the existing workflow, and the previous usage still …

[mattermost] Support running with channel names

---

README.md

This commit adds the perceval-gitee backend repo link to the list of community-maintained backends in the README.md file.
The support for grimoirelab-gitee was developed by @WillemJiang, @heming6666, @eyehwan, and @shanchenqi.
References
- https://github.com/chaoss/grimoirelab-perceval/issues/644
- https://github.com/chaoss/grimoirelab/pull/445

Add one community backend to Community components

---

perceval/backends/core/git.py
tests/test_git.py

This code adds argument `base-path` for git backend to decide path where the Git repositories will be cloned.
Version updated to 0.12.1
Fixes #758 
Signed-off-by: Fugang Xiao <xiao623@outlook.com>

[Git] Add argument `base-path` for git backend

---

README.md

This PR adds the airtable and bitbucket backend repository links to the Community Backends section in the README.md file.

[docs] Add Airtable and Bitbucket backends

---

README.md
docs/perceval/git.md

This commit adds documentation for using perceval against
private git repositories. The README.md and the read the docs
is updated with an example.
Signed-off-by: Jorge García Rey <jorgegar@inditex.com>

[docs] Add information for using perceval against private git repos

---

pyproject.toml

This PR adds the configurations of the metadata files to the `pyproject.toml` file. This is needed to include these files when the package is built using poetry.

Add configurations of the metadata files to pyproject.toml

---

perceval/backends/core/slack.py
releases/unreleased/slack-identifier-extraction-fixed.yml
tests/test_slack.py

This code fixes the `KeyError: username` when the user was removed.
when a user was deleted, the item doesn't have any user information,
so the "metadata_id" method will generate the identifier using only
the 'ts' value.

[slack] Fix username KeyError

---

perceval/backends/core/hyperkitty.py
perceval/backends/core/mbox.py
releases/unreleased/hyperkitty-to-date.yml
tests/test_hyperkitty.py

This code allows fetching data until a specific date by activating `--to-date`.
Backend version is now 0.7.0.
Tests added accordingly.

[hyperkitty/mbox] Activate '--to-date' argument

---

perceval/backends/core/mbox.py
releases/unreleased/default-value-for-mbox-to-date.yml
tests/test_mbox.py

This PR includes a default value for `--to-date` in mbox backend when the argument is not defined.
Related to https://github.com/chaoss/grimoirelab-perceval/issues/810

[mbox] Include a default value for `--to-date` in mbox backend

---

perceval/backends/core/confluence.py
releases/unreleased/add-token-auth-for-confluence.yml

Support token authentication for Confluence backend.
For Confluence Data Center or server editions, just use the personal access token:
`perceval confluence 'http://[YOUR_CONFLUENCE_SITE]/' -t [PERSONAL_ACCESS_TOKEN]`
For Confluence cloud:
`perceval confluence -u 'someone@example.com' -t [API_TOKEN] 'https://[YOUR_SITE].atlassian.net/wiki'`

Confluence token authentication

---

perceval/backends/core/jira.py
releases/unreleased/add-token-auth-for-jira.yml
tests/test_jira.py

For issue #813 .
Usage:
```
perceval jira <YOUR_JIRA_SERVER> -u <USERNAME> -p <PASSWORD>
perceval jira <YOUR_JIRA_SERVER> -t <PERSONAL_ACCESS_TOKEN>
perceval jira <YOUR_JIRA_CLOUD_SITE> -u <USERNAME> -t <TOKEN>
```

Jira token authentication

---

poetry.lock
pyproject.toml

This change is because there is a bug in urllib3 v2 with dulwich for Perceval.

Downgrade urllib3 from ^2.0.7 to ^1.26

---

perceval/backends/core/git.py
releases/unreleased/include-recovery-mode-for-git-backend.yml
tests/test_git.py

This PR implements the recovery functionality in the fetch method of the Git backend.
It also includes the last item search fields in the summary to allow recovering from the last item.

Recovery functionality for Git

---

.github/workflows/tests.yml
perceval/backends/core/git.py
releases/unreleased/wrong-filepath-for-movedcopied-files.yml
tests/data/git/git_log_moved.txt
tests/test_git.py

Stats about changes on a file were not reported correctly for files that where moved to a subdirectory. They were reported as an invalid entry and without action associated.
For example, the file `dir/filename` was moved to `dir/subdir/filename`, but it was reported as `dir//filename`. Therefore, the entry of the file `dir/subdire/filename` didn't have the stats about added and deleted lines. This error has been fixed and stats are reported correctly.

[git] Fix file stats for merged files on subdirs

---

perceval/backend.py
releases/unreleased/fixed-missing-backend-name-in-usage-string.yml

Fixes #799
I took a stab at this bug, by setting the `prog` attribute inside the `BackendCommand`'s `__init__` method, you ensure that the program name (prog) is set correctly when each backend is initialized. This should fix the issue with any backend.
```bash
$ perceval github -h
[2024-08-12 17:42:02,923] - Sir Perceval is on his quest.
usage: perceval github [-h] [--category CATEGORY] [--tag TAG] [--filter-classified] [--from-date FROM_DATE] [--to-date TO_DATE] [--archive-path ARCHIVE_PATH] [--no-archive] [--fetch-archive]
[--archived-since ARCHIVED_SINCE] [--no-ssl-verify] [-o OUTFILE] [--json-line] [--enterprise-url BASE_URL] [--sleep-for-rate] [--min-rate-to-sleep MIN_RATE_TO_SLEEP]
[-t API_TOKEN [API_TOKEN ...]] [--github-app-id GITHUB_APP_ID] [--github-app-pk-filepath …
```

Fix parsing and display of backend-specific help messages

---

perceval/backends/core/git.py
releases/unreleased/fix-issue-#782.yml
tests/test_git.py

title: 'Adding deletion for old tag references'
category: fixed
author: Matt Gaughan <mgaughan@proton.me>
issue:  (782)[https://github.com/chaoss/grimoirelab-perceval/issues/782]
notes: >
If server deletes reference to tag, local repo will as well. 
Simple implementation for clarity's sake.

Adding deletion for old tag references

---

perceval/backends/core/git.py
releases/unreleased/git-file-stats-with-whitespaces-were-not-assigned.yml
tests/data/git/git_log_merge.txt
tests/test_git.py

Git commit stats weren't assigned to the action for those files with whitespaces in their filenames.
Actions didn't have stats and empty stats entries were created, like in a merge commit.
The problem was that the regular expression used to parse the stats considered whitespaces as separators.

[git] Assign stats for files with whitespaces

---

perceval/backends/core/git.py
releases/unreleased/git-sync-perfomance-improved.yml

When repositories are synched, the backend needs to update the local references to the ones set on the remote repository. The backend processed all the references, including those up to date. This made the synchronization very slow.
With this commit, only the references that were updated on the remote repository will be modified locally. We have improved the performance by 2. Repositories are in sync two or more times than before.
Performance data using `https://github.com/eclipse-platform/eclipse.platform.releng.buildtools.git`, when the repository hasn't been updated.
- Before this patch
```
time perceval git https://github.com/eclipse-platform/eclipse.platform.releng.buildtools.git --latest-items
real	0m5,380s
user	0m1,802s
sys	0m2,000s
```
- Using this patch
```
time perceval git …
```

[git] Update references changed on the remote repo only

---

tests/test_git.py
tests/test_gitter.py

Some tests procuced some noise when the are run with 'run_tests.py' script. Data is send to '/dev/null' or similar.

[tests] Do not print data running 'run_tests.py'

---

.github/workflows/changelog.yml
.github/workflows/release.yml
CONTRIBUTING.md
README.md
docs/perceval/perceval-backends.md

Update files to support the migration of GrimoireLab repositories as part of the default branch transition from master to main.

Migrate files for branch rename from master to main

---

.github/workflows/release.yml
.github/workflows/tests.yml
perceval/backends/core/nntp.py
releases/unreleased/nntp-backend-removed.yml

`nntplib` is no longer part of the Python standard library. It was removed in Python 3.13 after being deprecated in Python 3.11 (PEP 594).
This PR adds a warning when using the NNTP backend to inform users of potential issues in future Python versions (>= 3.13), as nntplib has been removed from the standard library.
This PR also includes Python 3.13 in GitHub action tests
Related to https://github.com/chaoss/grimoirelab-perceval/issues/860

Deprecate NNTP backend

---

perceval/backends/core/git.py
releases/unreleased/git-filename-with-brackets-issue.yml
tests/data/git/git_log_brackets.txt
tests/data/git/git_log_moved_special_files.txt
tests/test_git.py

Perceval misinterpreted file paths containing curly brackets in the stats section of a log. It incorrectly detects them as renamed or moved. This was causing that the output contains new files that are not associated with any action.
This fix ensures that a file is only considered renamed if the file path contains '=>', reducing false positives of moved files.

[git] Fix filename parsing for files with brackets

---

perceval/backends/core/github.py
releases/unreleased/github-api-not-returning-issues.yml

GitHub API doesn't return issues using the default from date (1970-01-01)
This PR implements a temporary fix to prevent using the epoch time when fetching issues from the GitHub API.
Related to https://github.com/chaoss/grimoirelab-perceval/issues/865

[GitHub] Update default from-date to avoid issues with GitHub API

---

perceval/backends/core/github.py
releases/unreleased/github-api-pagination-bug.yml

Fixed a bug where pagination stopped working after the GitHub API stopped providing a reference to the last page.

[github] GitHub API pagination bug

---

perceval/backends/core/github.py
releases/unreleased/missing-user-at-github-api.yml
tests/test_github.py

This PR ensures that when the API returns a 404 for a user, Perceval returns the basic user data available in the related issue, pull request, comment, or review.

[github] Return basic user data when the API does not find the user

---

perceval/backends/core/git.py
releases/unreleased/git-moved-file-detection-issue-in-stats.yml
tests/data/git/git_log_merge_moved.txt
tests/data/git/git_log_moved_special_files.txt
tests/test_git.py

This PR fixes a bug that caused some moved files to be incorrectly detected in the commit file statistics.
Include all the special cases in tests.

[git] Fix moved file detection in stats

---

perceval/backends/core/jenkins.py
releases/unreleased/blacklist-option-for-builds-in-jenkins.yml
tests/test_jenkins.py

Add blacklist functionality for builds in Jenkins integration. To ignore a build, you must define the job name and the build id with the following format: `--blacklist-builds job-id:1234`

[jenkins] Add blacklist option for builds

---

.github/workflows/release.yml
.github/workflows/tests.yml
README.md
poetry.lock
pyproject.toml

Update workflows and configuration to support Python 3.10.
Python 3.9 will no longer receive updates after October 2025. This change ensures compatibility with newer features and maintains security for the project.

Update minimum Python version to 3.10

---

perceval/backends/core/git.py
releases/unreleased/new-trailers-for-git-commits.yml
tests/data/git/git_log_trailers.txt
tests/test_git.py

Expand the list of recognized trailers in Git using the ones listed by the Git documentation.

Add more trailer types for Git
